export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const AVATAR_UPDATE = 'AVATAR_UPDATE';

export const LOGIN_LOCAL = 'LOGIN_LOCAL';
export const LOGOUT_LOCAL = 'LOGOUT_LOCAL';
export const REGISTER_LOCAL = 'REGISTER_LOCAL';

export const SIDE_CUSTOMER_VIDEOS = 'SIDE_CUSTOMER_VIDEOS';
export const SIDE_CUSTOMER_SCHEDULE = 'SIDE_CUSTOMER_SCHEDULE';
export const SIDE_ACTIVE_PEOPLE = 'SIDE_ACTIVE_PEOPLE';

export const CLEAR_SIDE_CUSTOMER_VIDEOS = 'CLEAR_SIDE_CUSTOMER_VIDEOS';
export const CLEAR_SIDE_CUSTOMER_SCHEDULE = 'CLEAR_SIDE_CUSTOMER_VIDEOS';
export const CLEAR_SIDE_ACTIVE_PEOPLE = 'CLEAR_SIDE_CUSTOMER_VIDEOS';

export const COOKIE_BANNER_CONSENT = 'COOKIE_BANNER_CONSENT';
export const ROUTE_CURRENT_LOCATION = 'ROUTE_CURRENT_LOCATION';

